# K8s PI version
apiVersion: apps/v1
# Resource type
kind: Deployment
# Metadata about the deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  replicas: 2
  # Select Pod template labels
  # Selector is used to "select" the template to use (based on labels)
  selector:
    matchLabels:
      app: my-nginx
  # Template used to create the pods
  # Template to use to create the Pod/Containers (noe that the selector matches the label)
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      # Containers that will run in the pod
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
