apiVersion: v1
kind: Service
metadata:
  # Name of Service (each Service gets a DNS entry)
  name: nginx
  labels:
    app: nginx
spec:
  # Type of eservice (ClusterIP, NodePort, LoadBalancer) - defaults to ClusterIP
  type:

  # Select Pod template label(s) that service will apply to
  selector:
    # Service will apply to resources with a label of app: nginx
    app: nginx
  # Define container target port and the port for the service
  ports:
  - name: http
    port: 80
    targetPort: 80