apiVersion: v1
kind: Service
metadata:
  # Other Pods can use this FQDN to access the external service
  name: external-service
spec:
  # Set Service type to ExternalService
  type: ExternalName
  # Service will proxy to FQDN
  externalName: api.acmecorp.com
  ports:
  - port: 9000